/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistemadeventas.GUI;
import com.mycompany.sistemadeventas.Logica.Cliente;
import com.mycompany.sistemadeventas.Logica.EntidadFactory;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemadeventas.Data.ClienteDAO;
/**
 *
 * @author bruno
 */
public class clienteCRUD extends javax.swing.JInternalFrame {

    /**
     * Creates new form clienteCRUD
     */
     private ClienteDAO clienteDAO = new ClienteDAO();
    private DefaultTableModel modeloTabla;
    public clienteCRUD() {
        initComponents();
        initComponents();
        configurarTabla();
        cargarTabla();
        configurarSeleccionTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_correo = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JToggleButton();
        txt_id = new javax.swing.JTextField();
        bt_actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(this::bt_guardarActionPerformed);

        txt_id.setEditable(false);

        bt_actualizar.setText("Actualizar");
        bt_actualizar.addActionListener(this::bt_actualizarActionPerformed);

        jLabel1.setText("Rut");

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(this::bt_eliminarActionPerformed);

        jLabel2.setText("Nombre");

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(this::bt_cancelarActionPerformed);

        jLabel3.setText("Apellido");

        jLabel4.setText("Correo");

        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_clientes);

        jLabel5.setText("Numero");

        jLabel6.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_correo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txt_apellido)
                            .addComponent(txt_numero)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txt_nombre)
                            .addComponent(txt_id))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardar)
                    .addComponent(bt_actualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelar)
                    .addComponent(bt_eliminar))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        if (!validar()) return;
        Cliente c = EntidadFactory.crearCliente(
            txt_rut.getText().trim(),
            txt_nombre.getText().trim(),
            txt_apellido.getText().trim(),
            txt_correo.getText().trim(),
            txt_numero.getText().trim()
        );
        clienteDAO.guardar(c);
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.");
        limpiar();
        cargarTabla();
    
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void bt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizarActionPerformed
        if (tbl_clientes.getSelectedRow() < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla.");
            return;
        }
        if (!validar()) return;
        Cliente c = new Cliente(
            txt_rut.getText().trim(),
            txt_nombre.getText().trim(),
            txt_apellido.getText().trim(),
            txt_correo.getText().trim(),
            txt_numero.getText().trim()
        );
        clienteDAO.actualizar(c);
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
        limpiar();
        cargarTabla();
    
    }//GEN-LAST:event_bt_actualizarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        int fila = tbl_clientes.getSelectedRow();
        if (fila < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla.");
            return;
        }
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Eliminar este cliente?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            int id = (int) modeloTabla.getValueAt(fila, 0);
            clienteDAO.eliminar(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado.");
            limpiar();
            cargarTabla();
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed
private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new String[]{"ID", "RUT", "Nombre", "Apellido", "Correo", "Número"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        tbl_clientes.setModel(modeloTabla);
        tbl_clientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
private void configurarSeleccionTabla() {
        tbl_clientes.getSelectionModel().addListSelectionListener(e -> {
            int fila = tbl_clientes.getSelectedRow();
            if (fila >= 0) {
                txt_id.setText(String.valueOf(modeloTabla.getValueAt(fila, 0)));
                txt_rut.setText((String) modeloTabla.getValueAt(fila, 1));
                txt_nombre.setText((String) modeloTabla.getValueAt(fila, 2));
                txt_apellido.setText((String) modeloTabla.getValueAt(fila, 3));
                txt_correo.setText((String) modeloTabla.getValueAt(fila, 4));
                txt_numero.setText((String) modeloTabla.getValueAt(fila, 5));
            }
        });
    }
private void cargarTabla() {
        modeloTabla.setRowCount(0);
        List<Cliente> lista = clienteDAO.listarTodos();
        for (Cliente c : lista) {
            modeloTabla.addRow(new Object[]{
                c.getId(), c.getRut(), c.getNombre(),
                c.getApellido(), c.getCorreo(), c.getNumero()
            });
        }
    }
 private boolean validar() {
        if (txt_rut.getText().trim().isEmpty() ||
            txt_nombre.getText().trim().isEmpty() ||
            txt_apellido.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "RUT, Nombre y Apellido son obligatorios.", "Error",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
 private void limpiar() {
        txt_id.setText("");
        txt_rut.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_correo.setText("");
        txt_numero.setText("");
        tbl_clientes.clearSelection();
    }
 @SuppressWarnings("unchecked")
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JToggleButton bt_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
