/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistemadeventas.GUI;

import com.mycompany.sistemadeventas.Logica.Cliente;
import com.mycompany.sistemadeventas.Logica.Producto;
import com.mycompany.sistemadeventas.Logica.VentaFacade;
import com.mycompany.sistemadeventas.Logica.ventaProducto;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class productoVentas extends javax.swing.JInternalFrame implements VentaObserver {

    private final VentaFacade ventaFacade = new VentaFacade(VentaSubject.getInstance());
    private DefaultTableModel modeloVentas;

    /**
     * Creates new form productoVentas
     */
    public productoVentas() {
        initComponents();
        configurarTabla();
        cargarClientes();
        cargarProductos();
        cargarTablaVentas();

        // Nos suscribimos al Observer: si otra ventana registra una venta,
        // esta tabla y el stock mostrado se actualizan solos.
        VentaSubject.getInstance().agregarObservador(this);
        addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                VentaSubject.getInstance().quitarObservador(productoVentas.this);
            }
        });
    }

    private void configurarTabla() {
        modeloVentas = new DefaultTableModel(
                new String[]{"Cliente", "Producto", "Cantidad", "Precio Unit.", "Total", "Fecha"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbl_ventas.setModel(modeloVentas);
    }

    private void cargarClientes() {
        List<Cliente> lista = ventaFacade.listarClientes();
        DefaultComboBoxModel<Cliente> modelo = new DefaultComboBoxModel<>();
        for (Cliente c : lista) {
            modelo.addElement(c);
        }
        cb_clientes.setModel(modelo);
    }

    private void cargarProductos() {
        List<Producto> lista = ventaFacade.listarProductos();
        DefaultComboBoxModel<Producto> modelo = new DefaultComboBoxModel<>();
        for (Producto p : lista) {
            modelo.addElement(p);
        }
        cb_productos.setModel(modelo);
        actualizarPrecioUnitario();
    }

    private void cargarTablaVentas() {
        modeloVentas.setRowCount(0);
        List<ventaProducto> ventas = ventaFacade.listarVentas();
        for (ventaProducto v : ventas) {
            modeloVentas.addRow(new Object[]{
                v.getCliente().getNombre() + " " + v.getCliente().getApellido(),
                v.getProducto().getNombre(),
                v.getCantidad(),
                v.getProducto().getPrecio(),
                v.getTotal(),
                v.getFecha()
            });
        }
    }

    private void actualizarPrecioUnitario() {
        Producto p = (Producto) cb_productos.getSelectedItem();
        txt_preciounitario.setText(p != null ? String.valueOf(p.getPrecio()) : "");
        recalcularTotal();
    }

    private void recalcularTotal() {
        Producto p = (Producto) cb_productos.getSelectedItem();
        try {
            int cantidad = Integer.parseInt(cb_cantidad.getText().trim());
            if (p != null && cantidad > 0) {
                txt_total.setText(String.valueOf(p.getPrecio() * cantidad));
                return;
            }
        } catch (NumberFormatException ignored) {
            // El campo de cantidad aún no tiene un número válido
        }
        txt_total.setText("");
    }

    private void limpiar() {
        cb_cantidad.setText("");
        txt_total.setText("");
        if (cb_clientes.getItemCount() > 0) {
            cb_clientes.setSelectedIndex(0);
        }
        if (cb_productos.getItemCount() > 0) {
            cb_productos.setSelectedIndex(0);
        }
        actualizarPrecioUnitario();
    }

    /**
     * PATRÓN OBSERVER: se llama automáticamente cada vez que VentaFacade
     * registra una venta (en esta ventana o en cualquier otra).
     */
    @Override
    public void onNuevaVenta(ventaProducto venta) {
        cargarProductos();
        cargarTablaVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_clientes = new javax.swing.JComboBox<>();
        cb_productos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cb_cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_preciounitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        bt_registrar = new javax.swing.JButton();
        bt_actualizar = new javax.swing.JButton();

        cb_clientes.setModel(new javax.swing.DefaultComboBoxModel<com.mycompany.sistemadeventas.Logica.Cliente>());
        cb_clientes.addActionListener(this::cb_clientesActionPerformed);

        cb_productos.setModel(new javax.swing.DefaultComboBoxModel<com.mycompany.sistemadeventas.Logica.Producto>());
        cb_productos.addActionListener(this::cb_productosActionPerformed);

        jLabel1.setText("Cantidad");

        cb_cantidad.addActionListener(this::cb_cantidadActionPerformed);

        jLabel2.setText("Clientes");

        jLabel3.setText("Productos");

        jLabel4.setText("Precio unitario");

        txt_preciounitario.setEditable(false);
        txt_preciounitario.addActionListener(this::txt_preciounitarioActionPerformed);

        jLabel5.setText("Total");

        txt_total.addActionListener(this::txt_totalActionPerformed);

        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_ventas);

        bt_registrar.setText("Registrar venta");
        bt_registrar.addActionListener(this::bt_registrarActionPerformed);

        bt_actualizar.setText("Actualizar");
        bt_actualizar.addActionListener(this::bt_actualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(bt_registrar))
                        .addGap(18, 18, 18)
                        .addComponent(bt_actualizar)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_productos, 0, 109, Short.MAX_VALUE)
                                    .addComponent(cb_cantidad)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(53, 53, 53)
                                .addComponent(cb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_total)
                                    .addComponent(txt_preciounitario))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_preciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar)
                            .addComponent(bt_actualizar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        Cliente cliente = (Cliente) cb_clientes.getSelectedItem();
        Producto producto = (Producto) cb_productos.getSelectedItem();

        if (cliente == null || producto == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un cliente y un producto.", "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(cb_cantidad.getText().trim());
            if (cantidad <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La cantidad debe ser un número entero mayor a 0.", "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        ventaProducto venta = ventaFacade.realizarVenta(
                cliente.getRut(), producto.getNombre(), cantidad, new Date()
        );

        if (venta != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Venta registrada correctamente.");
            limpiar();
            // cargarProductos() y cargarTablaVentas() ya se ejecutan solos
            // vía onNuevaVenta() (Observer), no es necesario llamarlos aquí.
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo registrar la venta. Verifica que el cliente, el producto "
                    + "y el stock disponible sean correctos.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizarActionPerformed
        cargarClientes();
        cargarProductos();
        cargarTablaVentas();
    }//GEN-LAST:event_bt_actualizarActionPerformed

    private void cb_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_productosActionPerformed
        actualizarPrecioUnitario();
    }//GEN-LAST:event_cb_productosActionPerformed

    private void cb_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_clientesActionPerformed

    private void cb_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cantidadActionPerformed
        recalcularTotal();
    }//GEN-LAST:event_cb_cantidadActionPerformed

    private void txt_preciounitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_preciounitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_preciounitarioActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JTextField cb_cantidad;
    private javax.swing.JComboBox<Cliente> cb_clientes;
    private javax.swing.JComboBox<Producto> cb_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ventas;
    private javax.swing.JTextField txt_preciounitario;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
